-- MySQL Script generated by MySQL Workbench
-- Seg 11 Dez 2017 17:53:55 BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema iGanic
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `iGanic` ;

-- -----------------------------------------------------
-- Schema iGanic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iGanic` DEFAULT CHARACTER SET utf8 ;
USE `iGanic` ;

-- -----------------------------------------------------
-- Table `iGanic`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iGanic`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `iGanic`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `cel` VARCHAR(15) NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  `lat` DOUBLE NOT NULL,
  `lng` DOUBLE NOT NULL,
  `rua` VARCHAR(160) NOT NULL,
  `num` VARCHAR(20) NULL,
  `comp` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `uf` VARCHAR(20) NULL,
  `tipo` ENUM('C', 'F') NOT NULL,
  `usuario` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `rg_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iGanic`.`Produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iGanic`.`Produtos` ;

CREATE TABLE IF NOT EXISTS `iGanic`.`Produtos` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `unidade` VARCHAR(2) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `quantidade` DOUBLE NOT NULL,
  `modoProducao` VARCHAR(200) NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idProduto`),
  INDEX `fk_Produtos_Usuarios1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Produtos_Usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `iGanic`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iGanic`.`Imagens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iGanic`.`Imagens` ;

CREATE TABLE IF NOT EXISTS `iGanic`.`Imagens` (
  `idImagem` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `idProduto` INT NOT NULL,
  PRIMARY KEY (`idImagem`, `idProduto`),
  INDEX `fk_Imagens_Produtos1_idx` (`idProduto` ASC),
  CONSTRAINT `fk_Imagens_Produtos1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `iGanic`.`Produtos` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iGanic`.`Pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iGanic`.`Pedidos` ;

CREATE TABLE IF NOT EXISTS `iGanic`.`Pedidos` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `quantidade` FLOAT NOT NULL,
  `status` ENUM('A', 'C', 'F') NOT NULL COMMENT 'A - Andamento\nC - Cancelado\nF - Finalizado',
  `idUsuario` INT NOT NULL,
  `idProduto` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `idUsuario`),
  INDEX `fk_Pedidos_Usuarios1_idx` (`idUsuario` ASC),
  INDEX `fk_Pedidos_Produtos1_idx` (`idProduto` ASC),
  CONSTRAINT `fk_Pedidos_Usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `iGanic`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Produtos1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `iGanic`.`Produtos` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iGanic`.`Avaliacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iGanic`.`Avaliacoes` ;

CREATE TABLE IF NOT EXISTS `iGanic`.`Avaliacoes` (
  `idAvaliacao` INT NOT NULL AUTO_INCREMENT,
  `nota` INT NOT NULL,
  `comentario` VARCHAR(200) NULL,
  `idProduto` INT NOT NULL,
  PRIMARY KEY (`idAvaliacao`),
  INDEX `fk_Avaliacoes_Produtos1_idx` (`idProduto` ASC),
  CONSTRAINT `fk_Avaliacoes_Produtos1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `iGanic`.`Produtos` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
